# Generated by Django 3.1.3 on 2024-05-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiste',
            name='autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chiste',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
